# Generated by Django 3.2.14 on 2022-07-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_post_comment_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='c_funny',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='c_insightful',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='c_likes',
        ),
    ]
