# Generated by Django 3.2.14 on 2022-07-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_gamerreview_write'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='GamerReview',
        ),
        migrations.DeleteModel(
            name='Write',
        ),
    ]
