# Generated by Django 3.2.14 on 2022-07-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220722_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='excerpt',
            new_name='subtitle',
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.TextField(default=''),
        ),
    ]
