# Generated by Django 3.2.14 on 2022-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220723_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.CharField(max_length=100),
        ),
    ]
