# Generated by Django 3.2.14 on 2022-08-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220801_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='review',
            name='console',
            field=models.CharField(choices=[('PS5', 'PS5'), ('PS4', 'PS4'), ('XBOX', 'XBOX'), ('NDS', 'NDS'), ('PC', 'PC')], default='', max_length=4),
        ),
    ]
