# Generated by Django 3.2.14 on 2022-08-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220810_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='console',
            field=models.CharField(choices=[('ps5', 'PS5'), ('PS4', 'PS4'), ('xbox', 'XBOX'), ('nds', 'NDS'), ('pc', 'PC')], default='blank', max_length=4),
        ),
    ]
