# Generated by Django 3.2.14 on 2022-08-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20220810_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='console',
            field=models.CharField(choices=[('PS5', 'PS5'), ('PS4', 'PS4'), ('XBOX', 'XBOX'), ('NDS', 'NDS'), ('PC', 'PC')], default='', max_length=4),
        ),
    ]
