# Generated by Django 3.2.14 on 2022-08-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_review_console'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
