# Generated by Django 3.2.14 on 2022-08-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_alter_review_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='edit',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
